# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Collecture Landing Full Page
email: nickyniles@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  Welcome to Collecture.
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://lab27.github.io/cllctr-fllpg" # the base hostname & protocol for your site
twitter_username: flavrcrystals
github_username:  lab27

# Build settings
markdown: kramdown

# sass:
#   sass_dir: _sass
#   style: compressed


exclude:
  - package.json
  - node_modules
  - gulpfile.js